app/models.py
# from email.policy import default
from enum import unique
from unicodedata import category
from . import db
from flask_login import UserMixin,current_user
from sqlalchemy.sql import func
from werkzeug.security import generate_password_hash,check_password_hash
from . import login_manager
from datetime import datetime



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    blog = db.relationship('Blog', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref = 'user', lazy = 'dynamic')
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'{self.username}'


class Blog(db.Model):
    '''
    '''
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key = True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable = False)
    description = db.Column(db.String(), index = True)
    title = db.Column(db.String())
    category = db.Column(db.String())
    comments = db.relationship('Comment',backref='blogs',lazy='dynamic')
    
    
    @classmethod
    def get_blogs(cls, id):
        blogs = Blog.query.order_by(blog_id=id).desc().all()
        return blogs

    def __repr__(self):
        return f'Blog {self.description}'

class Comment(db.Model):
    __tablename__='comments'
    
    id = db.Column(db.Integer,primary_key=True)
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    description = db.Column(db.Text)

    
    def __repr__(self):
        return f"Comment : id: {self.id} comment: {self.description}"

app/main/forms.py
# from unicodedata import category
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import InputRequired

class BlogForm(FlaskForm):
	title = StringField('Title', validators=[InputRequired()])
	description = TextAreaField("write your blog here",validators=[InputRequired()])
	category = SelectField('select category', choices=[ ('general','general'), ('health','health')])
	submit = SubmitField('Submit')


class CommentForm(FlaskForm):
	description = TextAreaField('Add comment')
	submit = SubmitField()

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
# from flask_uploads import UploadSet,configure_uploads,IMAGES
# from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
# mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
# photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # mail.init_app(app)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

     # configure UploadSet
    # configure_uploads(app,photos)

    #Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    # mail.init_app(app)

    # Will add the views and forms
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

   

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from unicodedata import category
from flask import render_template,request,redirect,url_for,abort,flash

from app.main.forms import BlogForm, CommentForm
from . import main

from ..models import *

from flask_login import login_required,current_user
from .. import db
from flask.views import View,MethodView
import requests,json
# import markdown2


@main.route('/' ,methods = ['GET','POST'])
def index():
    form=CommentForm()
    quotes=requests.get("http://quotes.stormconsultancy.co.uk/random.json")
    data=json.loads(quotes.content)
    
    return render_template('home.html', form=form,data=data)


@main.route('/profile',methods = ['GET','POST'])
@login_required
def profile():
    
    return render_template("profile/profile.html")


@main.route('/write',methods = ['GET','POST'])
@login_required
def write():
    form=BlogForm()
    if form.validate_on_submit():
        description = form.description.data
        title = form.title.data
        owner_id = current_user
        category = form.category.data
        print(current_user._get_current_object().id)
        new_blog = Blog(owner_id =current_user._get_current_object().id, description=description,title=title,category=category)
        db.session.add(new_blog)
        db.session.commit()

    '''
    View root page function that returns the index page and its data
    '''
    blog = Blog.query.filter_by().first()
    title = 'Home'
    general = Blog.query.filter_by(category="general")
    health = Blog.query.filter_by(category = "health")

    
    return render_template("writer/writer.html",blog=blog,blog_form=form,general=general,health=health)

@main.route('/blogs/new',methods = ['GET','POST'])
def blogs():
    user=current_user
    blogs=Blog.query.all()
    form=CommentForm()
    if form.validate_on_submit():
        description = form.description.data
        title = form.title.data
        owner_id = current_user
        category = form.category.data
        print(current_user._get_current_object().id)
        new_blog = Blog(owner_id =current_user._get_current_object().id, title = title,description=description,category=category)
        db.session.add(new_blog)
        db.session.commit()
        
        return redirect(url_for('main.blogs'))
    return render_template("allblogs.html",comment_form=form,blogs=blogs)



@main.route('/comment/new/<int:blog_id>', methods = ['GET','POST'])
def comment(blog_id):
    form = CommentForm()
    blog=Blog.query.get(blog_id)
    if form.validate_on_submit():
        description = form.description.data

        new_comment = Comment(description = description)
        db.session.add(new_comment)
        db.session.commit()


        # return redirect(url_for('main.comment',blog_id=blog_id ))

    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    return render_template('comments.html', comment_form = form, comment = all_comments , blog=blog)


@main.route('/blog/<int:blog_id>/delete', methods=['GET','POST'])
@login_required
def delete_blog(blog_id):
  blog = Blog.query.get_or_404(blog_id)
  if blog.user != current_user:
    abort(403)
  db.session.delete(blog)
  db.session.commit()
  flash(f'Your post `Title: {blog.title}` has been Deleted!', 'info')
  return redirect(url_for('main.index'))

app/templates/allblogs.html
{% extends "base.html"%} {% import 'macros.html' as macro %} {% import
'bootstrap/wtf.html' as wtf%} {% block title%} HOME {% endblock%} {% block
styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" />

{% endblock %} {% block content %}
<h3 align="center" class="trend">TREDNING BLOGS</h3>


  <div class="comtainer-fluid blogs">
    <ul>
      
      {%for blog in blogs%}
      <li> <div class="card posted" style="width: 18rem">
    <div class="card-body">
      <h5 class="card-title">{{blog.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">Category:{{blog.category}}</h6>
      <p class="card-text">{{blog.description}}</p>
        
      </p>
      <a href="{{url_for('main.comment',blog_id=blog.id)}}" class="btn btn-primarycard-link"
        ><button type="button" class="btn btn-success">Add Comment</button></a
      >
      <a href="{{url_for('main.delete_blog',blog_id=blog.id)}}" class="card-link"
        ><button type="button" class="btn btn-danger">
          Delete<i class="fa-solid fa-trash-can"></i></button
      ></a>
    </div>
  </div>
  </li>
      {%endfor%}
      
    </ul>
    
 
  </div>
  {%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Indie+Flower&family=Mukta:wght@200&family=Poppins:ital,wght@1,200&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Sirin+Stencil&display=swap"
      rel="stylesheet"
    />
    <title>{% block title%}Home {%endblock%}</title>
    {% block styles%}

    <link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" />

    {% endblock %}
    <script
      src="https://kit.fontawesome.com/4b22a001a1.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar1">
      <div class="class1" id="navbar">
        <div class="items">
          {% if current_user.is_anonymous %}
          <a class="item" id=" home" href="/">Home</a>

          <a class="item" id=" blog" href="{{url_for('main.blogs')}}"> Blogs</a>
          <a class="item" id=" login" href="{{url_for('auth.login')}}">Login</a>
          <!-- <a class="item" id=" signUp" href="{{url_for('auth.register')}}"
            >sign Up</a
          > -->{%else%}
          <a class="item" id=" blog" href="{{url_for('main.blogs')}}"> Blogs</a>
          <a class="item" id=" blog" href="{{url_for('main.write')}}"
            >Write Blog</a
          >

          <a class="item" id=" logout" href="{{url_for('auth.logout')}}"
            >Log Out</a
          >
          {%endif%}
        </div>
      </div>
    </nav>

    {%block content%} {%endblock%}

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script>
      type = "text/javascript";
      ("{{url_for('static',filename='index.js')}}");
    </script>
  </body>
</html>

app/templates/blogs.html
{% extends "base.html"%} {% import 'macros.html' as macro %} {% import
'bootstrap/wtf.html' as wtf%} {% block title%} HOME {% endblock%} {% block
styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" />

{% endblock %} 
{% block content %}
this is a blog
{%endblock%}

app/templates/comments.html
{% extends "base.html"%} {% import 'macros.html' as macro %} {% import
'bootstrap/wtf.html' as wtf%} {% block title%} HOME {% endblock%} {% block
styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" />

{% endblock %} 
{% block content %}
<div class="login">
<div class="container"> 


  <div class="comments">
  <div class="row">
    <div class="card cardy">
      <div class="card-body text-center">
        <h4><a>{{blog.title}}</a></h4>
        <h5 class="card-text text-center">{{blog.description}}.</h5>
      </div>
    </div>

    <div class="container comm">
      <div class="row ">
        <div class="jumbotron tron">{{wtf.quick_form(comment_form)}}</div>
      </div>
    </div>

    <hr />
    <hr />
    <div class="container">
      <div class="col-md-12">
        <h4
          style="
            color:white;
            text-align: center;
            text-underline-position: below;
          "
        >
          Comments
        </h4>
        {{ macro.displayComment(comment) }}
      </div>
    </div>
  </div>
</div>
  
    <div class="row">
      <div class= "col-md-2">
         </div>
      <div class="col-md-8 logform">
      
      {{wtf.quick_form(comment_form)}}
      
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>
</div>
{%endblock%}

app/templates/home.html
{% extends "base.html"%} {% import 'macros.html' as macro %} {% import
'bootstrap/wtf.html' as wtf%} {% block title%} HOME {% endblock%} {% block
styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" />

{% endblock %} {% block content %}

<div class="image">
  <div class="row">
    <div class="col-md-2"> 
        
        <div class="card blog" style="width: 18rem">
    <div class="card-body">
      <h5 class="card-title">Quote Of Day<i class="fa-solid fa-pen-ruler"></i> </h5>
      <h6 class="card-subtitle mb-2 text-muted">Author:{{data.author}} </h6>
      Quote:{{data.quote}}
      </p>

    </div>
  </div>
    </div>
    <div class="col-md-4">
      <img src="../static/images/me.jpg" alt="me" id="me" />
    </div>
    <div class="col-md-4 things">
        <h2>10 THINGS I LOVE ABOUT SUNDAY</h2>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam
        incidunt enim beatae totam provident harum doloribus a, nobis dolorum
        similique est non reprehenderit dolor, et, error asperiores ea quas
        magnam. Lorem ipsum, dolor sit amet consectetur adipisicing elit.
        Ratione repellat, magni itaque odit voluptates atque. Rerum et magnam
        quos, quasi cupiditate vero, adipisci itaque saepe debitis, illo tempore
        exercitationem deleniti?
      </p>
      <br>
      <h3> View More Blogs</h3>
      <button type="button" class="btn btn-outline-success" align="center"><a href="{{url_for('main.blogs')}}">View Blogs</a> </button>
      
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
<br><br><br>
<div class="image">
  <div class="row">
    <div class="col-md-2"></div>
    
    <div class="col-md-4 things">
        <h2>Are You Passionate About Blogging?</h2>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam
        incidunt enim beatae totam provident harum doloribus a, nobis dolorum
        similique est non reprehenderit dolor, et, error asperiores ea quas
        magnam. Lorem ipsum, dolor sit amet consectetur adipisicing elit.
        Ratione repellat, magni itaque odit voluptates atque. Rerum et magnam
        quos, quasi cupiditate vero, adipisci itaque saepe debitis, illo tempore
        exercitationem deleniti?
      </p>
      <br>
      <h3>Share Your Blogs Here</h3>
      <button type="button" class="btn btn-outline-danger" align="center"><a href="{{url_for('main.write')}}">Write Blog</a> </button>
      
    </div>
    <div class="col-md-4">
      <img src="../static/images/write.jpg" alt="me" id="write" />
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
{%endblock%}

app/templates/macros.html
{% macro display(category_list) %}
<div class="row">
  {% if category_list %} {% for category in category_list %}
  <div class="col-md-6">
    <div class="thumbnail text-center">
      <h5 class="card-header">{{category.title}}</h5>
      <h5 class="card-header">{{category.category}}</h5>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <h2>{{category.description}}</h2>
          <footer class="blockquote-footer">
            Posted by {{category.user.username}}
          </footer>
        </blockquote>

        <a
          href="{{url_for('main.comment',blog_id = category.id)}}"
          class="btn btn-info"
        >
          Add a comment</a
        >
 
      </div>
    </div>
  </div>
  {% endfor %} {% else %} {% endif %}
</div>
{% endmacro %} {% macro displayComment(comments) %}
<ul>
  {% if comments %} {% for comment in comments %}
  <div class="row text-center">
    <a><p>{{ comment.description }}</p></a>
    <small> posted by {{comment.user.username}}</small>
  </div>
  {% endfor %} {% else %}

  <h3>This blog does not does not have any comments yet !</h3>
  {%endif%}
</ul>

{% endmacro %}

app/templates/others.html
<div class="comtainer-fluid blogs">
    
  <div class="card blog" style="width: 18rem">
    <div class="card-body">
      <h5 class="card-title">{{blogs.title }}</h5>i class="fa-solid fa-pen-ruler"></i> </h5>
      <h6 class="card-subtitle mb-2 text-muted">Posted By: Lucy</h6>
      <p class="card-text">{{blogs.description}}</p>
        Some quick example text to build on the card title and make up the bulk
        of the card's content.
      </p>
      <a href="{{url_for('main.comment')}}" class="card-link"
        ><button type="button" class="btn btn-success">Add Comment</button></a
      >
      <a href="#" class="card-link"
        ><button type="button" class="btn btn-danger">
          Delete<i class="fa-solid fa-trash-can"></i></button
      ></a>
    </div>
  </div>




    <div class="container">
    <div class="row">
      <div class="jumbotron">
        <ul style="list-style: none">
          {% for blog in blogs %}
          <div class="list-group">
            <a href="#">
              <div class="list-item">
                <p>{{blog.id}}</p>
              </div>
              <h4>{{ blog.description }}</h4>
              <h6>Posted by .</h6>
            </a>
          </div>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

app/templates/writer/writer.html
{% extends "base.html"%} {% import 'macros.html' as macro %} {% import
'bootstrap/wtf.html' as wtf%} {% block title%} HOME {% endblock%} {% block
styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" />

{% endblock %} 
{% block content %}
<div class="login">
<div class="container"> 
  
    <div class="row">
      <div class= "col-md-2">
         </div>
      <div class="col-md-8 logform">
      
      {{wtf.quick_form(blog_form)}}
  
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>
</div>
{%endblock%}